/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.mcalgovisualizations;

public class Library {
    public static boolean someLibraryMethod() {
        return true;
    }
}
